services:
    hugo_build:
        image: peaceiris/hugo:v0.146.0-full
        working_dir: /src
        environment:
            HUGO_ENV: production
            HUGO_ENVIRONMENT: production
            BASE_URL: ${BASE_URL:-http://localhost:8080}
        volumes:
            - ./:/src
            - public:/public
        command: >
            --gc --minify --destination /public --cleanDestinationDir --baseURL http://localhost:8080
        restart: "no"

    web:
        image: nginx:alpine
        # Start Nginx only after the build exits successfully
        depends_on:
            hugo_build:
                condition: service_completed_successfully
        volumes:
            - public:/usr/share/nginx/html:ro
            # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8080:80"
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://localhost/"]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: unless-stopped

volumes:
    public:
