services:
    - type: web
      name: hosting-render
      repo: https://github.com/jmooring/hosting-render
      runtime: static
      buildCommand: chmod a+x build.sh && ./build.sh
      staticPublishPath: public
      envVars:
          - key: DART_SASS_VERSION
            value: 1.91.0
          - key: GO_VERSION
            value: 1.25.0
          - key: HUGO_VERSION
            value: 0.149.0
          - key: NODE_VERSION
            value: 22.18.0
          - key: TZ
            value: Europe/Oslo
